
  CREATE TABLE IF NOT EXISTS "USER1"."TBL_BOOK" 
   (   "ID" NUMBER(19,0) NOT NULL ENABLE, 
   "AUTHOR" NVARCHAR2(50), 
   "COMP" NVARCHAR2(50), 
   "PRICE" NUMBER(10,0), 
   "TITLE" NVARCHAR2(120), 
    PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLOGTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BLOGTS" ;
  
  
   CREATE SEQUENCE IF NOT EXISTS "USER1"."SEQ_BBS"  
   START WITH 1 INCREMENT BY 1; 
  